# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

linter:
  rules:
  # Custom rules (uncomment to enable)
  # - avoid_print
  # - prefer_const_constructors
  # - prefer_final_locals

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

# Add more customization below if needed