name: adaptive_layout_manager
description: A Flutter package for adaptive layouts, font scaling, and responsive widgets across platforms.
version: 1.0.1
homepage: https://github.com/iameerhamza/adaptive_layout_manager

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true